### ISSUE TITLE
Time-dependent test

### ISSUE THREAD

**Issue by Yehouda** [sharplispers/scheduler#8]
https://github.com/sharplispers/scheduler/blob/bafc33cd99adc12b922870df3c51f9cbc927baff/scheduler-tests.lisp#L82

This check fails because by now **compute-next-occurance** doesn't find 1 Jan 2023. Instead it finds 2034 for me. 

Presumably you can just change it to 2034, and hope that the world comes to an end bfore that.....

BTW: it is "occurrence".

**Comment by dkochmanski** [comment]
haha, good one! :) thanks for the report. I'll fix it right away.
